# Alembic Configuration File
# This file is processed by alembic; any changes made here will be lost if
# alembic migrate command with --autogenerate is run again.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)d_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
sqlalchemy.url = driver://user:pass@localhost/dbname


# Logging configuration
# The above 'sqlalchemy.url' is the main thing; with tha alambic section, you can:
# - Provide the sqlalchemy connection url.
# - Provide additional named sqlalchemy.* options, which will be passed into
#   the create_engine() call when this script is executed from the command line
#   or if execute_setup_from_config is True.

[loggers]
keys = sqlalchemy.engine,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = INFO
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
